const $=id=>document.getElementById(id);const promptEl=$('prompt');const status=$('status');
const userId=()=>{let id=localStorage.getItem('qmw_user_id');if(!id){id='qmw_'+crypto.randomUUID();localStorage.setItem('qmw_user_id',id)}return id};
const payload=()=>({user_id:userId(),prompt:promptEl.value.trim(),kind:$('kind').value,target:$('target').value,quality:$('quality').value,target_fps:Number($('fps').value),ray_tracing:$('rt').checked,hdr:$('hdr').checked,upscaling:$('upscale').checked,assets:$('assets').checked,tests:$('tests').checked});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function busy(v,msg){$('plan').disabled=v;$('generate').disabled=v;$('topGenerate').disabled=v;status.textContent=msg}
function syncKind(kind){$('kind').value=kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x.dataset.kind===kind))}
$('count').textContent=promptEl.value.length;promptEl.addEventListener('input',()=>{$('count').textContent=promptEl.value.length});
document.querySelectorAll('[data-kind]').forEach(x=>x.addEventListener('click',()=>syncKind(x.dataset.kind)));
$('qualitySide').addEventListener('change',e=>$('quality').value=e.target.value);$('quality').addEventListener('change',e=>$('qualitySide').value=e.target.value);
$('fpsSide').addEventListener('change',e=>$('fps').value=e.target.value.replace(' FPS',''));
$('example').addEventListener('click',()=>{promptEl.value='Ein Open-World RPG in einer futuristischen Fantasy-Welt mit Spiegelwelten, dynamischem Wetter, eigenen Fraktionen, prozeduralen Quests, Bosskämpfen und einem intelligenten KI-Begleiter.';promptEl.dispatchEvent(new Event('input'));promptEl.focus()});
$('topGenerate').addEventListener('click',()=> $('generate').click());
$('plan').addEventListener('click',async()=>{if(promptEl.value.trim().length<3){promptEl.focus();return}busy(true,'● ENGINE · plane Welt & Systeme …');try{const r=await fetch('/api/generator/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const d=await r.json();if(!r.ok)throw Error(d.error);showPlan(d)}catch(e){status.textContent='● Fehler';alert(e.message)}finally{busy(false,status.textContent)}});
function showPlan(d){$('result').hidden=false;$('name').textContent=d.design.prompt.split(/\s+/).slice(0,8).join(' ');$('description').textContent='Dunkle-Spiegel Blueprint: deine Idee wurde in Game-Systeme, Welt, KI, Assets, Audio und Rendering zerlegt.';const b=d.blueprint;$('planbox').innerHTML=`<b>Pipeline:</b> ${d.quality.build_isolation_required?'Build-Isolation erforderlich':'Web Build'} · <b>Rendering:</b> ${esc(d.visual.resolution)} · ${d.visual.target_fps} FPS · HDR ${d.visual.hdr?'ON':'OFF'} · Raytracing ${d.visual.ray_tracing?'ON':'OFF'}<br><b>Welt:</b> ${esc(b.world.biomes.join(' · '))} · <b>NPC-KI:</b> ${esc(b.characters.npc_ai)}<br><b>Systeme:</b> ${esc(b.gameplay.systems.join(' · '))}`;status.textContent='● PLAN BEREIT'}
$('generate').addEventListener('click',async()=>{if(promptEl.value.trim().length<3){promptEl.focus();return}busy(true,'● KI ENGINE · generiere …');try{const r=await fetch('/api/generator/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const d=await r.json();if(!r.ok){if(r.status===402){status.textContent='● NICHT GENUG CREDITS';alert(`Für diese ${$('kind').value}-Generierung werden ${d.required_credits} Credits benötigt. Verfügbar: ${d.available_credits}. Credits kaufen: /credits`);return}throw Error(d.error)}$('result').hidden=false;$('name').textContent=d.name;$('description').textContent=d.description;$('download').href=d.download;$('files').innerHTML=(d.files||[]).map(x=>`<li><code>${esc(x)}</code></li>`).join('');$('steps').innerHTML=(d.next_steps||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('tests').innerHTML=(d.test_plan||[]).map(x=>`<li>${esc(x)}</li>`).join('');$('planbox').innerHTML=`<b>Credits:</b> −${d.credits_charged} · <b>Restguthaben:</b> ${d.credits_remaining} · <b>Rendering:</b> ${d.render_profile.resolution?.join(' × ')||'auto'} · <b>FPS:</b> ${d.target_fps}`;status.textContent='● GENERIERUNG FERTIG'}catch(e){status.textContent='● Fehler';alert(e.message)}finally{busy(false,status.textContent)}});
